name: Shuttle Run
description: "Runs a shuttle project."

inputs:
  cargo-shuttle-version:
    description: "Use a specific version of Shuttle."
    required: false
    default: ""
  secrets:
    description: "Contents of `Secrets.toml` file."
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: Install binstall.
      uses: cargo-bins/cargo-binstall@main

      
    - name: Install cargo-shuttle.
      if: ${{ inputs.cargo-shuttle-version == '' }}
      run: cargo binstall -y --locked cargo-shuttle
      shell: bash

    - name: Install cargo-shuttle with specific version.
      if: ${{ inputs.cargo-shuttle-version != '' }}
      run: cargo binstall -y --locked cargo-shuttle@${{ inputs.cargo-shuttle-version }}
      shell: bash
    

    - name: Create secrets.toml.
      if: ${{ inputs.secrets != '' }}
      run: echo "${{ inputs.secrets }}" > Secrets.toml
      shell: bash

    - name: Run project.
      run: cargo shuttle run &
      shell: bash

    - name: Check for server start
      run: |
        echo "Waiting for server to start..."
        timeout=60 # Timeout after 90 seconds
        interval=5 # Check every 5 seconds
        elapsed=0

        while ! curl --silent --fail localhost:8000; do
          sleep $interval
          elapsed=$((elapsed + interval))
          if [ $elapsed -ge $timeout ]; then
            echo "Server failed to start within $timeout seconds."
            exit 1
          fi
        done
        echo "Server is up and running."
      shell: bash
